---
dependencies: []

galaxy_info:
  author: dismorfo
  description: Chromium browser for Ubuntu
  company: "New York University"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu
      versions:
      - all
  galaxy_tags:
    - development
    - web


